<?php
/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Static FQCN → relative-path map used by the autoloader in
 * perflocale.php.
 *
 * @package PerfLocale
 */

declare( strict_types=1 );

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// phpcs:disable WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned -- single-space arrows keep the generated map compact.

return [
	'PerfLocale\\AbilitiesRegistrar' => 'AbilitiesRegistrar.php',
	'PerfLocale\\Activator' => 'Activator.php',
	'PerfLocale\\Addon\\AddonInterface' => 'Addon/AddonInterface.php',
	'PerfLocale\\Addon\\AddonManifestWriter' => 'Addon/AddonManifestWriter.php',
	'PerfLocale\\Addon\\AddonMigrationErrors' => 'Addon/AddonMigrationErrors.php',
	'PerfLocale\\Addon\\AddonRegistry' => 'Addon/AddonRegistry.php',
	'PerfLocale\\Addon\\AddonSchemaManager' => 'Addon/AddonSchemaManager.php',
	'PerfLocale\\Addon\\AddonSettings' => 'Addon/AddonSettings.php',
	'PerfLocale\\Addon\\AddonUninstaller' => 'Addon/AddonUninstaller.php',
	'PerfLocale\\Addon\\HasCardInfo' => 'Addon/HasCardInfo.php',
	'PerfLocale\\Addon\\HasCustomUninstall' => 'Addon/HasCustomUninstall.php',
	'PerfLocale\\Addon\\HasSchema' => 'Addon/HasSchema.php',
	'PerfLocale\\Addon\\HasUninstallTargets' => 'Addon/HasUninstallTargets.php',
	'PerfLocale\\Addon\\HasVersionRequirement' => 'Addon/HasVersionRequirement.php',
	'PerfLocale\\Addon\\PurgePlan' => 'Addon/PurgePlan.php',
	'PerfLocale\\Addon\\PurgeResult' => 'Addon/PurgeResult.php',
	'PerfLocale\\Admin\\AdminBarSwitcher' => 'Admin/AdminBarSwitcher.php',
	'PerfLocale\\Admin\\AdminController' => 'Admin/AdminController.php',
	'PerfLocale\\Admin\\Assets' => 'Admin/Assets.php',
	'PerfLocale\\Admin\\DashboardWidget' => 'Admin/DashboardWidget.php',
	'PerfLocale\\Admin\\DataExporter' => 'Admin/DataExporter.php',
	'PerfLocale\\Admin\\DataImporter' => 'Admin/DataImporter.php',
	'PerfLocale\\Admin\\EditorSidebar' => 'Admin/EditorSidebar.php',
	'PerfLocale\\Admin\\MetaBox' => 'Admin/MetaBox.php',
	'PerfLocale\\Admin\\Pages\\AddonsPage' => 'Admin/Pages/AddonsPage.php',
	'PerfLocale\\Admin\\Pages\\DashboardPage' => 'Admin/Pages/DashboardPage.php',
	'PerfLocale\\Admin\\Pages\\JobsPage' => 'Admin/Pages/JobsPage.php',
	'PerfLocale\\Admin\\Pages\\LanguagesPage' => 'Admin/Pages/LanguagesPage.php',
	'PerfLocale\\Admin\\Pages\\SettingsPage' => 'Admin/Pages/SettingsPage.php',
	'PerfLocale\\Admin\\Pages\\StringsPage' => 'Admin/Pages/StringsPage.php',
	'PerfLocale\\Admin\\Pages\\TranslationsPage' => 'Admin/Pages/TranslationsPage.php',
	'PerfLocale\\Admin\\PluginNav' => 'Admin/PluginNav.php',
	'PerfLocale\\Admin\\PoSync' => 'Admin/PoSync.php',
	'PerfLocale\\Admin\\PostListColumns' => 'Admin/PostListColumns.php',
	'PerfLocale\\Admin\\PrivacyIntegration' => 'Admin/PrivacyIntegration.php',
	'PerfLocale\\Admin\\QuarantineNotice' => 'Admin/QuarantineNotice.php',
	'PerfLocale\\Admin\\SiteHealth' => 'Admin/SiteHealth.php',
	'PerfLocale\\Admin\\TermListColumns' => 'Admin/TermListColumns.php',
	'PerfLocale\\Admin\\TermMetaBox' => 'Admin/TermMetaBox.php',
	'PerfLocale\\Admin\\TranslatorRole' => 'Admin/TranslatorRole.php',
	'PerfLocale\\Api\\BlockTranslateController' => 'Api/BlockTranslateController.php',
	'PerfLocale\\Api\\ConfigController' => 'Api/ConfigController.php',
	'PerfLocale\\Api\\JobsController' => 'Api/JobsController.php',
	'PerfLocale\\Api\\LanguagesController' => 'Api/LanguagesController.php',
	'PerfLocale\\Api\\MachineTranslateController' => 'Api/MachineTranslateController.php',
	'PerfLocale\\Api\\RestController' => 'Api/RestController.php',
	'PerfLocale\\Api\\StringsController' => 'Api/StringsController.php',
	'PerfLocale\\Api\\TranslationsController' => 'Api/TranslationsController.php',
	'PerfLocale\\Api\\WebhookController' => 'Api/WebhookController.php',
	'PerfLocale\\Api\\XliffController' => 'Api/XliffController.php',
	'PerfLocale\\Background\\AbstractJob' => 'Background/AbstractJob.php',
	'PerfLocale\\Background\\ActionSchedulerRunner' => 'Background/ActionSchedulerRunner.php',
	'PerfLocale\\Background\\BackgroundEvents' => 'Background/BackgroundEvents.php',
	'PerfLocale\\Background\\Dispatcher' => 'Background/Dispatcher.php',
	'PerfLocale\\Background\\JobCanceledException' => 'Background/JobCanceledException.php',
	'PerfLocale\\Background\\JobLock' => 'Background/JobLock.php',
	'PerfLocale\\Background\\JobRunnerFactory' => 'Background/JobRunnerFactory.php',
	'PerfLocale\\Background\\JobRunnerInterface' => 'Background/JobRunnerInterface.php',
	'PerfLocale\\Background\\JobState' => 'Background/JobState.php',
	'PerfLocale\\Background\\Jobs\\BulkStringTranslateJob' => 'Background/Jobs/BulkStringTranslateJob.php',
	'PerfLocale\\Background\\Jobs\\BulkTranslateJob' => 'Background/Jobs/BulkTranslateJob.php',
	'PerfLocale\\Background\\Jobs\\DataExportJob' => 'Background/Jobs/DataExportJob.php',
	'PerfLocale\\Background\\Jobs\\DataImportJob' => 'Background/Jobs/DataImportJob.php',
	'PerfLocale\\Background\\Jobs\\PolylangMigrationJob' => 'Background/Jobs/PolylangMigrationJob.php',
	'PerfLocale\\Background\\Jobs\\SiteTranslateJob' => 'Background/Jobs/SiteTranslateJob.php',
	'PerfLocale\\Background\\Jobs\\StringScanJob' => 'Background/Jobs/StringScanJob.php',
	'PerfLocale\\Background\\Jobs\\TranslatePressMigrationJob' => 'Background/Jobs/TranslatePressMigrationJob.php',
	'PerfLocale\\Background\\Jobs\\WpmlMigrationJob' => 'Background/Jobs/WpmlMigrationJob.php',
	'PerfLocale\\Background\\MigrationCacheHelper' => 'Background/MigrationCacheHelper.php',
	'PerfLocale\\Background\\Resumer' => 'Background/Resumer.php',
	'PerfLocale\\Background\\WorkerRegistry' => 'Background/WorkerRegistry.php',
	'PerfLocale\\Background\\WpCronRunner' => 'Background/WpCronRunner.php',
	'PerfLocale\\Bootstrap' => 'Bootstrap.php',
	'PerfLocale\\Cache\\CacheInvalidator' => 'Cache/CacheInvalidator.php',
	'PerfLocale\\Cache\\CacheManager' => 'Cache/CacheManager.php',
	'PerfLocale\\Cli\\AddonCommand' => 'Cli/AddonCommand.php',
	'PerfLocale\\Cli\\AddonSettingsCommand' => 'Cli/AddonSettingsCommand.php',
	'PerfLocale\\Cli\\PerfLocaleCommand' => 'Cli/PerfLocaleCommand.php',
	'PerfLocale\\Concurrency\\Breaker' => 'Concurrency/Breaker.php',
	'PerfLocale\\Concurrency\\BreakerOpenException' => 'Concurrency/BreakerOpenException.php',
	'PerfLocale\\Concurrency\\Lock' => 'Concurrency/Lock.php',
	'PerfLocale\\Contract\\RepositoryInterface' => 'Contract/RepositoryInterface.php',
	'PerfLocale\\Database\\Migrator' => 'Database/Migrator.php',
	'PerfLocale\\Database\\Repository\\LanguageRepository' => 'Database/Repository/LanguageRepository.php',
	'PerfLocale\\Database\\Repository\\MigrationSourceMapRepository' => 'Database/Repository/MigrationSourceMapRepository.php',
	'PerfLocale\\Database\\Repository\\SlugTranslationRepository' => 'Database/Repository/SlugTranslationRepository.php',
	'PerfLocale\\Database\\Repository\\StringRepository' => 'Database/Repository/StringRepository.php',
	'PerfLocale\\Database\\Repository\\StringTranslationRepository' => 'Database/Repository/StringTranslationRepository.php',
	'PerfLocale\\Database\\Repository\\TranslationGroupRepository' => 'Database/Repository/TranslationGroupRepository.php',
	'PerfLocale\\Database\\Repository\\TranslationLinkRepository' => 'Database/Repository/TranslationLinkRepository.php',
	'PerfLocale\\Database\\Schema' => 'Database/Schema.php',
	'PerfLocale\\Database\\SiteCleanup' => 'Database/SiteCleanup.php',
	'PerfLocale\\Deactivator' => 'Deactivator.php',
	'PerfLocale\\Enum\\ObjectType' => 'Enum/ObjectType.php',
	'PerfLocale\\Enum\\SourceType' => 'Enum/SourceType.php',
	'PerfLocale\\Enum\\TranslationStatus' => 'Enum/TranslationStatus.php',
	'PerfLocale\\Frontend\\Assets' => 'Frontend/Assets.php',
	'PerfLocale\\Frontend\\CacheTagEmitter' => 'Frontend/CacheTagEmitter.php',
	'PerfLocale\\Frontend\\ConditionalContent' => 'Frontend/ConditionalContent.php',
	'PerfLocale\\Frontend\\ContentLanguageHeader' => 'Frontend/ContentLanguageHeader.php',
	'PerfLocale\\Frontend\\CustomizerIntegration' => 'Frontend/CustomizerIntegration.php',
	'PerfLocale\\Frontend\\HreflangTags' => 'Frontend/HreflangTags.php',
	'PerfLocale\\Frontend\\LanguageSwitcher' => 'Frontend/LanguageSwitcher.php',
	'PerfLocale\\Frontend\\LanguageSwitcherBlock' => 'Frontend/LanguageSwitcherBlock.php',
	'PerfLocale\\Frontend\\LanguageSwitcherWidget' => 'Frontend/LanguageSwitcherWidget.php',
	'PerfLocale\\Frontend\\LocaleDateFormat' => 'Frontend/LocaleDateFormat.php',
	'PerfLocale\\Frontend\\SlugRedirector' => 'Frontend/SlugRedirector.php',
	'PerfLocale\\Frontend\\SpeculationRulesEmitter' => 'Frontend/SpeculationRulesEmitter.php',
	'PerfLocale\\Frontend\\ViewTransitionsEmitter' => 'Frontend/ViewTransitionsEmitter.php',
	'PerfLocale\\Helper' => 'Helper.php',
	'PerfLocale\\MachineTranslation\\AbstractProvider' => 'MachineTranslation/AbstractProvider.php',
	'PerfLocale\\MachineTranslation\\CostEstimator' => 'MachineTranslation/CostEstimator.php',
	'PerfLocale\\MachineTranslation\\MetaTranslator' => 'MachineTranslation/MetaTranslator.php',
	'PerfLocale\\MachineTranslation\\ProviderInterface' => 'MachineTranslation/ProviderInterface.php',
	'PerfLocale\\MachineTranslation\\Provider\\DeepLProvider' => 'MachineTranslation/Provider/DeepLProvider.php',
	'PerfLocale\\MachineTranslation\\Provider\\ExternalAgencyProvider' => 'MachineTranslation/Provider/ExternalAgencyProvider.php',
	'PerfLocale\\MachineTranslation\\Provider\\GoogleProvider' => 'MachineTranslation/Provider/GoogleProvider.php',
	'PerfLocale\\MachineTranslation\\Provider\\LibreTranslateProvider' => 'MachineTranslation/Provider/LibreTranslateProvider.php',
	'PerfLocale\\MachineTranslation\\Provider\\MicrosoftProvider' => 'MachineTranslation/Provider/MicrosoftProvider.php',
	'PerfLocale\\MachineTranslation\\Provider\\WpAiClientProvider' => 'MachineTranslation/Provider/WpAiClientProvider.php',
	'PerfLocale\\MachineTranslation\\TranslationService' => 'MachineTranslation/TranslationService.php',
	'PerfLocale\\Migration\\PolylangImporter' => 'Migration/PolylangImporter.php',
	'PerfLocale\\Migration\\TranslatePressImporter' => 'Migration/TranslatePressImporter.php',
	'PerfLocale\\Migration\\WpmlImporter' => 'Migration/WpmlImporter.php',
	'PerfLocale\\Plugin' => 'Plugin.php',
	'PerfLocale\\Router\\GeoRedirect' => 'Router/GeoRedirect.php',
	'PerfLocale\\Router\\LanguageRouter' => 'Router/LanguageRouter.php',
	'PerfLocale\\Router\\RewriteManager' => 'Router/RewriteManager.php',
	'PerfLocale\\Router\\SlugManager' => 'Router/SlugManager.php',
	'PerfLocale\\Router\\UrlConverter' => 'Router/UrlConverter.php',
	'PerfLocale\\Seo\\HreflangManager' => 'Seo/HreflangManager.php',
	'PerfLocale\\Seo\\OgLocale' => 'Seo/OgLocale.php',
	'PerfLocale\\Seo\\SchemaEnricher' => 'Seo/SchemaEnricher.php',
	'PerfLocale\\Seo\\SitemapIntegration' => 'Seo/SitemapIntegration.php',
	'PerfLocale\\Seo\\SitemapRenderer' => 'Seo/SitemapRenderer.php',
	'PerfLocale\\Settings' => 'Settings.php',
	'PerfLocale\\Strings\\PluralRules' => 'Strings/PluralRules.php',
	'PerfLocale\\Strings\\StringScanner' => 'Strings/StringScanner.php',
	'PerfLocale\\Strings\\StringTranslation' => 'Strings/StringTranslation.php',
	'PerfLocale\\Strings\\TranslationFileGenerator' => 'Strings/TranslationFileGenerator.php',
	'PerfLocale\\Strings\\TranslationFileLoader' => 'Strings/TranslationFileLoader.php',
	'PerfLocale\\Translation\\BlockSkipFilter' => 'Translation/BlockSkipFilter.php',
	'PerfLocale\\Translation\\ContentChangeDetector' => 'Translation/ContentChangeDetector.php',
	'PerfLocale\\Translation\\ContentSync' => 'Translation/ContentSync.php',
	'PerfLocale\\Translation\\FallbackSnippetGuard' => 'Translation/FallbackSnippetGuard.php',
	'PerfLocale\\Translation\\MediaTranslationManager' => 'Translation/MediaTranslationManager.php',
	'PerfLocale\\Translation\\MenuManager' => 'Translation/MenuManager.php',
	'PerfLocale\\Translation\\MtRateLimiter' => 'Translation/MtRateLimiter.php',
	'PerfLocale\\Translation\\PlaceholderMasker' => 'Translation/PlaceholderMasker.php',
	'PerfLocale\\Translation\\PostQueryFilter' => 'Translation/PostQueryFilter.php',
	'PerfLocale\\Translation\\PostTranslationManager' => 'Translation/PostTranslationManager.php',
	'PerfLocale\\Translation\\TermAssignmentFilter' => 'Translation/TermAssignmentFilter.php',
	'PerfLocale\\Translation\\TermQueryFilter' => 'Translation/TermQueryFilter.php',
	'PerfLocale\\Translation\\TermTranslationManager' => 'Translation/TermTranslationManager.php',
	'PerfLocale\\Util\\PathRedactor' => 'Util/PathRedactor.php',
	'PerfLocale\\Util\\SecretMasker' => 'Util/SecretMasker.php',
	'PerfLocale\\Util\\SprintfTokens' => 'Util/SprintfTokens.php',
	'PerfLocale\\WooCommerce\\EmailTranslation' => 'WooCommerce/EmailTranslation.php',
	'PerfLocale\\WooCommerce\\ExchangeRateSync' => 'WooCommerce/ExchangeRateSync.php',
	'PerfLocale\\WooCommerce\\InventorySync' => 'WooCommerce/InventorySync.php',
	'PerfLocale\\WooCommerce\\LocaleCurrency' => 'WooCommerce/LocaleCurrency.php',
	'PerfLocale\\WooCommerce\\MultiCurrency' => 'WooCommerce/MultiCurrency.php',
	'PerfLocale\\WooCommerce\\WcStringTranslation' => 'WooCommerce/WcStringTranslation.php',
	'PerfLocale\\Xliff\\XliffExporter' => 'Xliff/XliffExporter.php',
	'PerfLocale\\Xliff\\XliffFormatException' => 'Xliff/XliffFormatException.php',
	'PerfLocale\\Xliff\\XliffImporter' => 'Xliff/XliffImporter.php',
];
