<?php
/**
 * Editor-script dependencies for the perflocale/language-switcher block.
 *
 * Normally generated by @wordpress/scripts at build time. Since this
 * plugin uses hand-written JS (no build step), we ship the asset file
 * directly so WP's block.json loader knows the real dependency set.
 *
 * @package PerfLocale
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return [
	'dependencies' => [
		'wp-blocks',
		'wp-block-editor',
		'wp-components',
		'wp-element',
		'wp-i18n',
		'wp-server-side-render',
	],
	'version' => defined( 'PERFLOCALE_VERSION' ) ? PERFLOCALE_VERSION : '1.0.0',
];
